/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ArcNewsComponent {
    'abstract': string;
    'apiUrl': string;
    'img': string;
    'link': string;
    'newsDate': string;
    'newsTitle': string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLArcNewsComponentElement extends Components.ArcNewsComponent, HTMLStencilElement {}
  var HTMLArcNewsComponentElement: {
    prototype: HTMLArcNewsComponentElement;
    new (): HTMLArcNewsComponentElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'arc-news-component': HTMLArcNewsComponentElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface ArcNewsComponent extends JSXBase.HTMLAttributes<HTMLArcNewsComponentElement> {
    'abstract'?: string;
    'apiUrl'?: string;
    'img'?: string;
    'link'?: string;
    'newsDate'?: string;
    'newsTitle'?: string;
  }
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'arc-news-component': ArcNewsComponent;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


